version: "3.8"
services:
  db:
    container_name: eatclean_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user
    ports:
      - "5434:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"


  redis:
    container_name: redis-doan
    image: redis:6.2.5-alpine
    restart: always
    ports:
      - 6379:6379